Mount Google drive

In [1]:
# Run the following lines for Google Colab to mount your Google drive
# from google.colab import drive
# drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Import libraries

In [2]:
import pandas as pd

Load train data

In [3]:
# Load the training dataset
#train_data_path = '/content/drive/My Drive/Hackathon/Train_set_(1).csv'
train_data_path = '/mnt/data/Train_set_(1).csv'
train_data = pd.read_csv(train_data_path)

# Display the first few rows of the training dataset and its summary
train_data.head(), train_data.info(), train_data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93174 entries, 0 to 93173
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          93174 non-null  int64
 1   loan_amnt                   93174 non-null  int64
 2   loan_term                   93174 non-null  object
 3   interest_rate               93174 non-null  float64
 4   loan_grade                  93174 non-null  object
 5   loan_subgrade               93174 non-null  object
 6   job_experience              88472 non-null  object
 7   home_ownership              93174 non-null  object
 8   annual_income               93173 non-null  float64
 9   income_verification_status  93174 non-null  object
 10  loan_purpose                93174 non-null  object
 11  state_code                  93174 non-null  object
 12  debt_to_income              93174 non-null  float64
 13  delinq_2yrs                 93172 non-null  float64
 14  public_records              93172 non-null  float64
 15  revolving_balance           93174 non-null  int64
 16  total_acc                   93172 non-null  float64
 17  interest_receive            93174 non-null  float64
 18  application_type            93174 non-null  object
 19  last_week_pay               91250 non-null  float64
 20  total_current_balance       85788 non-null  float64
 21  total_revolving_limit       85788 non-null  float64
 22  default                     93174 non-null  int64
dtypes: float64(10), int64(4), object(9)
memory usage: 16.3+ MB

(         ID  loan_amnt loan_term  interest_rate loan_grade loan_subgrade  \
 0  72199369       9000   3 years           9.17          B            B2
 1  14257956      18000   3 years          13.65          C            C1
 2  66216451      16000   3 years           7.26          A            A4
 3  46974169      25000   3 years          13.99          C            C4
 4  46725961      17000   3 years           6.39          A            A2

   job_experience home_ownership  annual_income income_verification_status  \
 0       <5 Years            OWN        85000.0               Not Verified
 1       <5 Years            OWN        64000.0                   Verified
 2       <5 Years       MORTGAGE       150000.0            Source Verified
 3            NaN       MORTGAGE        59800.0                   Verified
 4      10+ years       MORTGAGE        72000.0            Source Verified

    ... delinq_2yrs public_records  revolving_balance  total_acc  \
 0  ...         0.0            0.0              39519       20.0
 1  ...         0.0            1.0               9783       24.0
 2  ...         2.0            0.0              13641       27.0
 3  ...         0.0            0.0              35020       35.0
 4  ...         0.0            0.0              23990       26.0

    interest_receive  application_type  last_week_pay  total_current_balance  \
 0             59.60        INDIVIDUAL            4.0                95493.0
 1           3348.25        INDIVIDUAL           95.0               185433.0
 2            276.69        INDIVIDUAL           13.0               180519.0
 3           1106.72        INDIVIDUAL           17.0               183208.0
 4            725.29        INDIVIDUAL           39.0                23990.0

   total_revolving_limit  default
 0               84100.0        0
 1               13500.0        0
 2               19300.0        0
 3               55400.0        0
 4               81300.0        0

 [5 rows x 23 columns],
 None,
                  ID     loan_amnt  interest_rate  annual_income  \
 count  9.317400e+04  93174.000000   93174.000000   9.317300e+04
 mean   3.505021e+07  14733.861378      13.233433   7.502826e+04
 std    2.414926e+07   8428.184858       4.368728   6.945478e+04
 min    7.073500e+04    500.000000       5.320000   1.200000e+03
 25%    1.085983e+07   8000.000000       9.990000   4.500000e+04
 50%    3.710751e+07  13000.000000      12.990000   6.400000e+04
 75%    5.859895e+07  20000.000000      16.200000   9.000000e+04
 max    7.351975e+07  35000.000000      28.990000   9.500000e+06

        debt_to_income   delinq_2yrs  public_records  revolving_balance  \
 count    93174.000000  93172.000000    93172.000000       9.317400e+04
 mean        18.127623      0.316994        0.196121       1.685447e+04
 std          8.563084      0.880859        0.581188       2.368907e+04
 min          0.000000      0.000000        0.000000       0.000000e+00
 25%         11.930000      0.000000        0.000000       6.433000e+03
 50%         17.640000      0.000000        0.000000       1.185600e+04
 75%         23.890000      0.000000        0.000000       2.074500e+04
 max        672.520000     22.000000       49.000000       2.560703e+06

           total_acc  interest_receive  last_week_pay  total_current_balance  \
 count  93172.000000      93174.000000   91250.000000           8.578800e+04
 mean      25.248905       1747.263530      58.154882           1.392529e+05
 std       11.855061       2088.236141      44.326560           1.576868e+05
 min        1.000000          0.000000       0.000000           0.000000e+00
 25%       17.000000        439.880000      22.000000           2.964200e+04
 50%       24.000000       1070.755000      48.000000           7.936350e+04
 75%       32.000000       2219.612500      83.000000           2.071600e+05
 max      119.000000      23172.310000     291.000000           8.000078e+06

        total_revolving_limit       default
 count           8.578800e+04  93174.000000
 mean            3.208590e+04      0.237502
 std             4.705251e+04      0.425555
 min             0.000000e+00      0.000000
 25%             1.400000e+04      0.000000
 50%             2.370000e+04      0.000000
 75%             3.970000e+04      0.000000
 max             9.999999e+06      1.000000  )

Load test data

In [4]:
# Load the test dataset
# test_data_path = '/content/drive/My Drive/Hackathon/Test_set_(1).csv'
test_data_path = '/mnt/data/Test_set_(1).csv'
test_data = pd.read_csv(test_data_path)

# Display the first few rows of the test dataset and its summary
test_data.head(), test_data.info(), test_data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39933 entries, 0 to 39932
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          39933 non-null  int64
 1   loan_amnt                   39933 non-null  int64
 2   loan_term                   39933 non-null  object
 3   interest_rate               39933 non-null  float64
 4   loan_grade                  39933 non-null  object
 5   loan_subgrade               39933 non-null  object
 6   job_experience              37844 non-null  object
 7   home_ownership              39933 non-null  object
 8   annual_income               39933 non-null  float64
 9   income_verification_status  39933 non-null  object
 10  loan_purpose                39933 non-null  object
 11  state_code                  39933 non-null  object
 12  debt_to_income              39933 non-null  float64
 13  delinq_2yrs                 39932 non-null  float64
 14  public_records              39932 non-null  float64
 15  revolving_balance           39933 non-null  int64
 16  total_acc                   39932 non-null  float64
 17  interest_receive            39933 non-null  float64
 18  application_type            39933 non-null  object
 19  last_week_pay               39127 non-null  float64
 20  total_current_balance       36703 non-null  float64
 21  total_revolving_limit       36703 non-null  float64
dtypes: float64(10), int64(3), object(9)
memory usage: 6.7+ MB

(         ID  loan_amnt loan_term  interest_rate loan_grade loan_subgrade  \
 0   4855329      12000   3 years          15.31          C            C2
 1  66862420      12000   3 years           7.26          A            A4
 2   3637416      15000   3 years          14.33          C            C1
 3  53682249      12000   3 years           9.99          B            B3
 4  53937165      20150   3 years          11.53          B            B5

   job_experience home_ownership  annual_income income_verification_status  \
 0       <5 Years       MORTGAGE        73400.0               Not Verified
 1      10+ years       MORTGAGE       105000.0               Not Verified
 2     6-10 years       MORTGAGE        50000.0                   Verified
 3     6-10 years           RENT        37000.0            Source Verified
 4       <5 Years           RENT        75000.0            Source Verified

    ... debt_to_income delinq_2yrs  public_records  revolving_balance  \
 0  ...          14.62         0.0             0.0              22156
 1  ...          11.38         0.0             0.0               7592
 2  ...          28.15         0.0             1.0              17983
 3  ...          34.32         0.0             0.0              12262
 4  ...          26.74         1.0             0.0               8251

    total_acc  interest_receive  application_type  last_week_pay  \
 0       30.0           2290.24        INDIVIDUAL           87.0
 1       14.0            202.68        INDIVIDUAL           13.0
 2       19.0           1166.24        INDIVIDUAL           30.0
 3       18.0            635.06        INDIVIDUAL           35.0
 4       11.0           1232.84        INDIVIDUAL           31.0

   total_current_balance  total_revolving_limit
 0              128098.0                25800.0
 1              269396.0                23600.0
 2              220135.0                34100.0
 3               39436.0                21700.0
 4               52764.0                12000.0

 [5 rows x 22 columns],
 None,
                  ID     loan_amnt  interest_rate  annual_income  \
 count  3.993300e+04  39933.000000   39933.000000   3.993300e+04
 mean   3.481149e+07  14781.987329      13.219258   7.526480e+04
 std    2.421750e+07   8427.845431       4.392109   5.655666e+04
 min    7.430100e+04    500.000000       5.320000   3.300000e+03
 25%    1.075172e+07   8000.000000       9.990000   4.526200e+04
 50%    3.680509e+07  13000.000000      12.990000   6.500000e+04
 75%    5.845998e+07  20000.000000      16.200000   9.000000e+04
 max    7.351969e+07  35000.000000      28.990000   5.000000e+06

        debt_to_income   delinq_2yrs  public_records  revolving_balance  \
 count    39933.000000  39932.000000    39932.000000       3.993300e+04
 mean        18.121058      0.312256        0.191526       1.701928e+04
 std          8.487992      0.854545        0.557824       2.612974e+04
 min          0.000000      0.000000        0.000000       0.000000e+00
 25%         11.960000      0.000000        0.000000       6.482000e+03
 50%         17.610000      0.000000        0.000000       1.194900e+04
 75%         23.880000      0.000000        0.000000       2.092800e+04
 max        380.530000     17.000000       23.000000       2.568995e+06

           total_acc  interest_receive  last_week_pay  total_current_balance  \
 count  39932.000000      39933.000000   39127.000000           3.670300e+04
 mean      25.264825       1764.743917      58.418177           1.404625e+05
 std       11.768501       2095.443444      44.476130           1.565759e+05
 min        1.000000          0.000000       0.000000           0.000000e+00
 25%       17.000000        441.470000      22.000000           2.980700e+04
 50%       24.000000       1077.720000      48.000000           8.059000e+04
 75%       32.000000       2260.990000      83.000000           2.095905e+05
 max      114.000000      21811.290000     278.000000           3.881449e+06

        total_revolving_limit
 count           3.670300e+04
 mean            3.245321e+04
 std             6.183545e+04
 min             0.000000e+00
 25%             1.400000e+04
 50%             2.390000e+04
 75%             4.010000e+04
 max             9.999999e+06  )

Check data types and missing values

In [5]:
# Checking data types and missing values
data_info = train_data.info()
missing_values = train_data.isnull().sum()

# Summary statistics for numerical features
numerical_summary = train_data.describe()

# Exploring the distribution of the target variable
target_distribution = train_data['default'].value_counts(normalize=True)

data_info, missing_values, numerical_summary, target_distribution

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93174 entries, 0 to 93173
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          93174 non-null  int64
 1   loan_amnt                   93174 non-null  int64
 2   loan_term                   93174 non-null  object
 3   interest_rate               93174 non-null  float64
 4   loan_grade                  93174 non-null  object
 5   loan_subgrade               93174 non-null  object
 6   job_experience              88472 non-null  object
 7   home_ownership              93174 non-null  object
 8   annual_income               93173 non-null  float64
 9   income_verification_status  93174 non-null  object
 10  loan_purpose                93174 non-null  object
 11  state_code                  93174 non-null  object
 12  debt_to_income              93174 non-null  float64
 13  delinq_2yrs                 93172 non-null  float64
 14  public_records              93172 non-null  float64
 15  revolving_balance           93174 non-null  int64
 16  total_acc                   93172 non-null  float64
 17  interest_receive            93174 non-null  float64
 18  application_type            93174 non-null  object
 19  last_week_pay               91250 non-null  float64
 20  total_current_balance       85788 non-null  float64
 21  total_revolving_limit       85788 non-null  float64
 22  default                     93174 non-null  int64
dtypes: float64(10), int64(4), object(9)
memory usage: 16.3+ MB

(None,
 ID                               0
 loan_amnt                        0
 loan_term                        0
 interest_rate                    0
 loan_grade                       0
 loan_subgrade                    0
 job_experience                4702
 home_ownership                   0
 annual_income                    1
 income_verification_status       0
 loan_purpose                     0
 state_code                       0
 debt_to_income                   0
 delinq_2yrs                      2
 public_records                   2
 revolving_balance                0
 total_acc                        2
 interest_receive                 0
 application_type                 0
 last_week_pay                 1924
 total_current_balance         7386
 total_revolving_limit         7386
 default                          0
 dtype: int64,
                  ID     loan_amnt  interest_rate  annual_income  \
 count  9.317400e+04  93174.000000   93174.000000   9.317300e+04
 mean   3.505021e+07  14733.861378      13.233433   7.502826e+04
 std    2.414926e+07   8428.184858       4.368728   6.945478e+04
 min    7.073500e+04    500.000000       5.320000   1.200000e+03
 25%    1.085983e+07   8000.000000       9.990000   4.500000e+04
 50%    3.710751e+07  13000.000000      12.990000   6.400000e+04
 75%    5.859895e+07  20000.000000      16.200000   9.000000e+04
 max    7.351975e+07  35000.000000      28.990000   9.500000e+06

        debt_to_income   delinq_2yrs  public_records  revolving_balance  \
 count    93174.000000  93172.000000    93172.000000       9.317400e+04
 mean        18.127623      0.316994        0.196121       1.685447e+04
 std          8.563084      0.880859        0.581188       2.368907e+04
 min          0.000000      0.000000        0.000000       0.000000e+00
 25%         11.930000      0.000000        0.000000       6.433000e+03
 50%         17.640000      0.000000        0.000000       1.185600e+04
 75%         23.890000      0.000000        0.000000       2.074500e+04
 max        672.520000     22.000000       49.000000       2.560703e+06

           total_acc  interest_receive  last_week_pay  total_current_balance  \
 count  93172.000000      93174.000000   91250.000000           8.578800e+04
 mean      25.248905       1747.263530      58.154882           1.392529e+05
 std       11.855061       2088.236141      44.326560           1.576868e+05
 min        1.000000          0.000000       0.000000           0.000000e+00
 25%       17.000000        439.880000      22.000000           2.964200e+04
 50%       24.000000       1070.755000      48.000000           7.936350e+04
 75%       32.000000       2219.612500      83.000000           2.071600e+05
 max      119.000000      23172.310000     291.000000           8.000078e+06

        total_revolving_limit       default
 count           8.578800e+04  93174.000000
 mean            3.208590e+04      0.237502
 std             4.705251e+04      0.425555
 min             0.000000e+00      0.000000
 25%             1.400000e+04      0.000000
 50%             2.370000e+04      0.000000
 75%             3.970000e+04      0.000000
 max             9.999999e+06      1.000000  ,
 0    0.762498
 1    0.237502
 Name: default, dtype: float64)

Treat missing values

In [6]:
# Handling missing values

# Numerical columns: Impute with median
numerical_cols = train_data.select_dtypes(include=['float64', 'int64']).columns
train_data[numerical_cols] = train_data[numerical_cols].fillna(train_data[numerical_cols].median())

# Categorical columns: Impute with mode
categorical_cols = train_data.select_dtypes(include=['object']).columns
for col in categorical_cols:
    train_data[col] = train_data[col].fillna(train_data[col].mode()[0])

# Check if there are any missing values left
missing_values_after = train_data.isnull().sum()

missing_values_after

ID                            0
loan_amnt                     0
loan_term                     0
interest_rate                 0
loan_grade                    0
loan_subgrade                 0
job_experience                0
home_ownership                0
annual_income                 0
income_verification_status    0
loan_purpose                  0
state_code                    0
debt_to_income                0
delinq_2yrs                   0
public_records                0
revolving_balance             0
total_acc                     0
interest_receive              0
application_type              0
last_week_pay                 0
total_current_balance         0
total_revolving_limit         0
default                       0
dtype: int64

Treat outliers

In [7]:
# Treating outliers using the Interquartile Range (IQR) method

for col in numerical_cols:
    # Calculating IQR
    Q1 = train_data[col].quantile(0.25)
    Q3 = train_data[col].quantile(0.75)
    IQR = Q3 - Q1

    # Defining the boundary for outliers
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Capping outliers
    train_data[col] = train_data[col].clip(lower=lower_bound, upper=upper_bound)

# Checking summary statistics again to see the effect of outlier treatment
numerical_summary_after_outliers = train_data[numerical_cols].describe()
numerical_summary_after_outliers

,ID,loan_amnt,interest_rate,annual_income,debt_to_income,delinq_2yrs,public_records,revolving_balance,total_acc,interest_receive,last_week_pay,total_current_balance,total_revolving_limit,default
count,9.317400e+04,93174.000000,93174.000000,93174.000000,93174.000000,93174.0,93174.0,93174.000000,93174.000000,93174.000000,93174.000000,93174.000000,93174.000000,93174.0
mean,3.505021e+07,14733.861378,13.228829,71435.787760,18.119930,0.0,0.0,15025.403675,25.089070,1551.378491,57.613653,127573.690104,28621.557677,0.0
std,2.414926e+07,8428.184858,4.354859,34608.952733,8.286843,0.0,0.0,11264.546806,11.347554,1429.223650,42.765022,121810.595101,18776.542566,0.0
min,7.073500e+04,500.000000,5.320000,1200.000000,0.000000,0.0,0.0,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0
25%,1.085983e+07,8000.000000,9.990000,45000.000000,11.930000,0.0,0.0,6433.000000,17.000000,439.880000,22.000000,31953.000000,14700.000000,0.0
50%,3.710751e+07,13000.000000,12.990000,64000.000000,17.640000,0.0,0.0,11856.000000,24.000000,1070.755000,48.000000,79363.500000,23700.000000,0.0
75%,5.859895e+07,20000.000000,16.200000,90000.000000,23.890000,0.0,0.0,20745.000000,32.000000,2219.612500,83.000000,194994.750000,37875.000000,0.0
max,7.351975e+07,35000.000000,25.515000,157500.000000,41.830000,0.0,0.0,42213.000000,54.500000,4889.211250,174.500000,439557.375000,72637.500000,0.0

Apply one-hot encoding to categorical variables

In [8]:
from sklearn.preprocessing import OneHotEncoder

# Identifying categorical variables
categorical_cols = train_data.select_dtypes(include=['object']).columns

# Applying one-hot encoding to categorical variables
encoder = OneHotEncoder(sparse=False, drop='first')  # drop first to avoid multicollinearity
encoded_categorical = encoder.fit_transform(train_data[categorical_cols])

# Creating a DataFrame with encoded categorical variables
encoded_categorical_df = pd.DataFrame(encoded_categorical,
                                      columns=encoder.get_feature_names_out(categorical_cols))

# Dropping original categorical columns and concatenating the encoded ones
train_data_encoded = train_data.drop(categorical_cols, axis=1)
train_data_encoded = pd.concat([train_data_encoded, encoded_categorical_df], axis=1)

train_data_encoded.head()

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,ID,loan_amnt,interest_rate,annual_income,debt_to_income,delinq_2yrs,public_records,revolving_balance,total_acc,interest_receive,...,state_code_TN,state_code_TX,state_code_UT,state_code_VA,state_code_VT,state_code_WA,state_code_WI,state_code_WV,state_code_WY,application_type_JOINT
0,72199369,9000,9.17,85000.0,26.68,0.0,0.0,39519,20.0,59.60,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,14257956,18000,13.65,64000.0,31.67,0.0,0.0,9783,24.0,3348.25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,66216451,16000,7.26,150000.0,19.70,0.0,0.0,13641,27.0,276.69,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,46974169,25000,13.99,59800.0,37.39,0.0,0.0,35020,35.0,1106.72,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,46725961,17000,6.39,72000.0,8.92,0.0,0.0,23990,26.0,725.29,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Handle the class imbalance

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

# Redefining features (X) and target variable (y)
X = train_data_encoded.drop('default', axis=1)
y = train_data_encoded['default']



# Random Forest model with class_weight set to 'balanced'
rf_model = RandomForestClassifier(random_state=42, class_weight='balanced')

# Redefining the training and validation sets without SMOTE
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Training the Random Forest model on the training set
rf_model.fit(X_train, y_train)

# Making predictions on the validation set
y_val_pred = rf_model.predict(X_val)

# Calculating accuracy on the validation set
accuracy_rf = accuracy_score(y_val, y_val_pred)
accuracy_rf

1.0

Tune hyperparameter

In [10]:
from sklearn.model_selection import GridSearchCV

# Parameters to tune
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Grid search with cross-validation
rf_grid_search = GridSearchCV(estimator=RandomForestClassifier(random_state=42, class_weight='balanced'),
                              param_grid=param_grid,
                              cv=5,  # 5-fold cross-validation
                              scoring='accuracy',
                              n_jobs=-1)  # use all processors

# Fitting the grid search to the data
rf_grid_search.fit(X_train, y_train)

# Best parameters and best accuracy
best_params = rf_grid_search.best_params_
best_accuracy = rf_grid_search.best_score_

best_params, best_accuracy

({'max_depth': 10,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'n_estimators': 50},
 1.0)